#!/bin/sh

# Usage: git commit-date "message" "date"
# Example: git commit-date "Add new feature" "2023-05-01T12:00:00"

echo "Setting commit date to $1"

commit_date="$1"

if [ -z "$commit_date" ]; then
    echo "Error: Commit date is required."
    exit 1
fi

export GIT_AUTHOR_DATE="$commit_date"
export GIT_COMMITTER_DATE="$commit_date"

git commit --amend

unset GIT_AUTHOR_DATE
unset GIT_COMMITTER_DATE
