#!/bin/bash

add_six_months() {
    date -u -d"$1 + 6 months" +%Y-%m-%dT%H:%M:%S
}

export -f add_six_months

git filter-branch --force --env-filter '
OLD_AUTHOR_DATE=$GIT_AUTHOR_DATE
OLD_COMMITTER_DATE=$GIT_COMMITTER_DATE

GIT_AUTHOR_DATE=$(add_six_months "$OLD_AUTHOR_DATE")
GIT_COMMITTER_DATE=$(add_six_months "$OLD_COMMITTER_DATE")

export GIT_AUTHOR_DATE
export GIT_COMMITTER_DATE
' -- --all
